FriendsOfSymfony/FOSRestBundle

Resources/config/schema/routing-1.0.xsd
Resources/config/schema/routing/rest_routing-1.0.xsd
Routing/Loader/RestXmlCollectionLoader.php
Tests/Routing/Loader/RestXmlCollectionLoaderTest.php
Tests/Routing/Loader/RestYamlCollectionLoaderTest.php

* sync xsd wit a symfony one
* allow symfony loader to load unrecognized routes (This works for yaml out of the box, but not for xml, because the routes reside in different namespace)

allow symfony loader to load it's unrecognized routes

---

Resources/doc/1-setting_up_the_bundle.rst

*The Symfony Documenators started an initiative to make all bundle installation documentation consistent and  easy to understand for beginners. That'll improve the DX for starters using 3rd party bundles. The template can be found here: http://symfony.com/doc/current/cookbook/bundles/best_practices.html#installation-instructions*
I would like to ask you to use this template in your documentation.
If you have any comments on the template, please open an issue in the `symfony/symfony-docs` repository. Feedback will brings us to the ultimate template.

Use standard bundle installation template

---

Resources/doc/1-setting_up_the_bundle.rst
Resources/doc/3-listener-support.rst
Resources/doc/5-automatic-route-generation_single-restful-controller.rst
Resources/doc/index.rst

The main change of this PR is that the `index.rst` now includes a hidden TOC. This is mandatory to avoid Sphinx/reStructuredText errors.
In FOSUserBundle doc we added a [real visible TOC](https://github.com/javiereguiluz/FOSUserBundle/commit/70c20da51000ab30df520f5e50e177fa113a791f#diff-fdd764ee72f777e180ace83412a44158R459) because it makes sense in its doc. In FOSRestBundle case it doesn't make sense, so the trick is to include a hidden TOC.

Fixed some minor issues with the new RST doc

---

EventListener/ParamFetcherListener.php
Tests/EventListener/ParamFetcherListenerTest.php
Tests/Fixtures/Controller/ParamFetcherController.php

This (finally) addresses @stof's comment about [my previous PR](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/745https://github.com/FriendsOfSymfony/FOSRestBundle/pull/745).

Allow the user to typehint using `ParamFetcherInterface`

---

Routing/Loader/RestYamlCollectionLoader.php
Tests/Fixtures/Routes/routes_with_options_requirements_and_defaults.xml
Tests/Fixtures/Routes/routes_with_options_requirements_and_defaults.yml
Tests/Routing/Loader/RestXmlCollectionLoaderTest.php
Tests/Routing/Loader/RestYamlCollectionLoaderTest.php

This pull request adds tests that the collection loaders (both XML and YAML) forward route requirements and defaults when importing a controller, like the forwarding of options already works.
This mirrors the behavior of the [symfony `YamlFileLoader`](https://github.com/symfony/symfony/blob/ac389b67145e26f99a59a06bad7346ab5e2ec097/src/Symfony/Component/Routing/Loader/YamlFileLoader.php#L172-173) and [`XmlFileLoader`](https://github.com/symfony/symfony/blob/ac389b67145e26f99a59a06bad7346ab5e2ec097/src/Symfony/Component/Routing/Loader/XmlFileLoader.php#L181-182)
Adding these tests uncovered a flaw in `RestYamlCollectionLoader`, which does not forward these requirements or defaults. The `RestXmlCollectionLoader` does not contain this flaw, because it calls the symfony `XmlFileLoader`.

[bugfix] Forward requirements and defaults in RestYamlCollectionLoader

---

Resources/doc/2-the-view-layer.rst
Tests/View/ViewHandlerTest.php
Tests/View/ViewTest.php
View/View.php
View/ViewHandler.php

This is an alternative way of adding template variable to views (see also #936).
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #936
| License       | MIT
| Doc PR        |
TODO:
In short, the `View` now have `setTemplateData` along with `setData`, so that additional data can be passed to templating formats, without affecting other format (e.g. serializer).
`setTemplateData` can either be an associative array, or a callable which return the array.
Example using a simple array:
```php
$viewData = array('category' => $category);
$viewData['other_template_data'] = $otherTemplateData;
return $this->view($products, 200)
->setTemplate("AcmeDemoBundle:Category:show.html.twig") …
```

Pass additional variables in template system with lazy-loading

---

DependencyInjection/Compiler/ExceptionWrapperHandlerPass.php
FOSRestBundle.php
Tests/FOSRestBundleTest.php

This compiler pass removes the `ExceptionWrapperSerializeHandler` if the JMS serializer is not present.

remove unusable handler when JMS serializer is not present

---

.travis.yml
Tests/Functional/SerializerErrorTest.php

These lines were copied by mistake from the above tests.
They are needed to hide the logged exception messages when running the tests but useless here because no exception is thrown when submitting the invalid form.

Removed useless ini_set in tests

---

Resources/config/view.xml
Tests/DependencyInjection/FOSRestExtensionTest.php

As per @xabbuh's comment https://github.com/FriendsOfSymfony/FOSRestBundle/pull/975#discussion_r25566085, we should follow Symfony and not include class parameters for new services classes.
This PR removes the class parameter introduced here https://github.com/FriendsOfSymfony/FOSRestBundle/pull/975

Removed parameter for exception normalizer class

---

Controller/Annotations/Param.php
Request/ParamFetcher.php
Resources/doc/3-listener-support.rst
Resources/doc/annotations-reference.rst
Tests/Controller/Annotations/QueryParamTest.php
Tests/Request/ParamFetcherTest.php

to QueryParam to detect parameters that can't appears
together in the same API call

close #901, we can add a incompatibles attribute

---

Form/Transformer/EntityToIdObjectTransformer.php
Resources/doc/2-the-view-layer.rst

According to the issue (https://github.com/FriendsOfSymfony/FOSRestBundle/issues/984) I created a transformer that can handle serialized objects containing an id and map it to the entity.
The use of this transfomer within a form type would look as follows:
```php
$transformer = new EntityToIdObjectTransformer($this->om, "AcmeDemoBundle:MyEntity");
$builder->add($builder->create('myfield', 'text')->addModelTransformer($transformer))
```
This way, the selialization process stays untouched.
Not sure if this it's generic enough, otherwise it's documented here at least.

DataTransformer to transform serialized objects containing an id to it's entity

---

.travis.yml

Currently, PHP 7 doesn't come with the Xdebug extension and thus cannot
generate code coverage reports. Hence, sending them to Scrutinizer CI
must be disabled on such builds.

don't send code coverage reports on PHP 7 builds

---

composer.json

fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/973

due to an issue in LegacyValidator we disallow early 2.5.x releases

---

.travis.yml
composer.json

* remove unneeded shell wrapper
* run a Travis build with lowest dependency versions
* allow to finish as fast as possible (when either a mandatory build
failed or when only builds allowed to fail have not completed yet)

update Travis CI configuration

---

.gitignore
Request/ParamFetcher.php
Tests/Request/ParamFetcherTest.php

fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1013
Example Usage: 
```php
@QueryParam(name="parent_id", requirements={"rule" = "\d+", "error_message" = "parent_id must be an integer"}, strict=true, nullable=true, description="Parent Id")
```
Error Message:
```json
{
"code": 400,
"message": "parent_id must be an integer"
}
```

Added new feature for nice error messages to ParamFetcher

---

Routing/RestRouteCollection.php

Scenario:
`config.yml`:
fos_rest:
format_listener: true
routing_loader:
default_format: json
`ReportController.php` (simplified)
/**
* @Rest\Get("/report/export", defaults = {"_format": "xlsx"}, requirements = {"_format": "xlsx|csv|json|xml"})
*/
public function exportAction(Report $report, HttpFoundation\Request $request) {
return $this->get('report.exporter')->getReponse($report, $request->getRequestFormat('xlsx'));
}
Annotation sets default format to `xlsx`, but `FOS\RestBundle\Routing\Loader\RestRouteLoader::load()` after reading all routes invokes `FOS\RestBundle\Routing\RestRouteCollection::setDefaultFormat()` which overrides it with global `default_format` from bundle config. When `/report/export` is accessed without format, global `default_format` is used even if there is custom …

Setting default format in RestRouteCollection.php only if not set already

---

Resources/doc/3-listener-support.rst

The `fos_rest` config was referring `my_body_listener`, but the service was declared as `my.body_listener`.

Fix Typo in custom service listener example

---

Request/AbstractRequestBodyParamConverter.php

If the previous exception is not injected in the new one (as it was the case), part of the stack trace is lost.

[BodyParamConverter] Preserve previous exception on deserialize fail

---

EventListener/MimeTypeListener.php
Tests/EventListener/MimeTypeListenerTest.php

Wrong format. "enabled" value format due to new structure of configuration.

Fix old use of mime_types configuration

---

Controller/Annotations/Route.php
Routing/Loader/Reader/RestActionReader.php
Tests/Fixtures/Etalon/annotated_conditional_controller.yml
Tests/Fixtures/Etalon/annotated_users_controller.yml
Tests/Fixtures/Etalon/named_prefixed_reports_collection.yml
Tests/Fixtures/Etalon/prefixed_users_collection.yml
Tests/Fixtures/Etalon/resource_controller.yml
Tests/Fixtures/Etalon/users_collection.yml
Tests/Fixtures/Etalon/users_controller.yml
Tests/Routing/Loader/RestRouteLoaderTest.php
Tests/Routing/Loader/RestXmlCollectionLoaderTest.php
Tests/Routing/Loader/RestYamlCollectionLoaderTest.php

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1051 
| License       | MIT

Fixed deprecated _method errors

---

Routing/Loader/RestYamlCollectionLoader.php
Tests/Fixtures/Etalon/base_named_prefixed_reports_collection.yml
Tests/Fixtures/Routes/base_named_prefixed_reports_collection.yml
Tests/Routing/Loader/RestYamlCollectionLoaderTest.php

Fixed error when name prefix ignored in yaml. Issue #1029.
I check the example from Issue #1029, and I think the problem is inheritance class don't save parent name_prefix. I have the same problem, and my solution in this pull request.
With an app/console router:debug, we have:
```
get_first                         GET      ANY    ANY  /api/v1/first
get_second                        GET      ANY    ANY  /api/v1/second
```
If we save parent name prefix the result will be:
```
api_v1_get_first                         GET      ANY    ANY  /api/v1/first
api_v1_get_second                        GET      ANY    ANY  /api/v1/second
```

Fixed error when name prefix ignored in yaml. Issue #1029

---

Resources/doc/format_listener.rst

The raw yaml configuration for mime types with version could be painful with a lot of versions and mime types to manage.
I propose to introduce a php tricks I made on the documentation to show this alternative to users.
Feel free to comment my PR! :+1: 
Regards

mime_types configuration script for versions

---

DependencyInjection/Compiler/SerializerConfigurationPass.php
Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php

Right now, if we're using the Symfony serializer and there's the JMS's one registered too for any reason, we can't due to a serializer normalizer not removed:
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                               
The service "serializer" has a dependency on a non-existent service "fos_rest.serializer.exception_wrapper_normalizer".  
```
This PR fixes the problem.

Allow to use Symfony's serializer even with JMS Serializer enabled

---

Resources/doc/param_fetcher_listener.rst

you forgot a comma in the documentation.

syntax error in documentation

---

Controller/Annotations/RouteResource.php
Resources/doc/5-automatic-route-generation_single-restful-controller.rst
Routing/Loader/Reader/RestActionReader.php
Routing/Loader/Reader/RestControllerReader.php
Tests/Fixtures/Controller/AnnotatedNonPluralizedArticleController.php
Tests/Routing/Loader/RestRouteLoaderTest.php

I decided to create a new PR about #294 because #531 seems to be abandoned.
This PR add the support of non-pluralized resource names as described in #294.
You can use it like that:
```php
<?php
/**
*  @Rest\RouteResource(resource="Article", pluralize=false)
*/
class FooController extends FosRestController
{
public function cgetAction()
{} // [GET] /article
public function getAction($slug)
{} // [GET] /article/{slug}
public function cgetCommentAction($slug)
{} // [GET] /article/{slug}/comment
}
```

Add support of non-pluralized resource names

---

Request/ParamFetcher.php
Tests/Request/ParamFetcherTest.php

Currently, the regex used for requirements is automatically surrounded by characters `^` and `$` (see [`ParamFetcher.php` code](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Request/ParamFetcher.php#L216)). It seems legit and very helpful, since wen can easily write `A+` to match at least one `A`, or even `A` if we expect only one occurence.
Unfortunately, this helper may introduce a misunderstanding of what really happens in the case where we want to match an `A` **or** a `B` character. Our first guess will be `A|B`, but is is **wrong**. This requirement will produce the regex `^A|B$`, matching all strings starting by `A` **or** finishing by `B`.
This behavior is absolutely normal, this is not a bug, but IMHO it is counter-intuitive (then, dangerous). In the previous …

Surrounded requirements regex by parenthesis

---

Request/ParamFetcher.php
Resources/config/request.xml
Resources/doc/param_fetcher_listener.rst
Tests/Request/ParamFetcherTest.php

See #1039 
Note: contains a BC break as the container has been injected into the ParamFetcher as a required argument

Allow use of placeholders as requirements in Query/RequestParam

---

Controller/ExceptionController.php

This PR fixes the last deprecated call to ``ContainerInterface::get('request')``.
It fixes #824 at the same time.

Remove a deprecated call to ContainerInterface::get('request')

---

Form/Transformer/EntityToIdObjectTransformer.php

this fixes a tiny "display" bug concerning non-numeric identifiers (like GUID)

fixed error message for non numeric identifiers

---

.gitignore
.php_cs
composer.json

This bridge permits contributors to fix CS using PHP-CS-Fixer command line while keeping same configuration as `.styleci.yml` file.

StyleCI / PHP-CS-Fixer bridge

---

.travis.yml
composer.json

FOSRestBundle does not rely on the full Symfony Security component, but
only uses a few classes from the `symfony/security-core` package.

require only needed Symfony security components

---

.travis.yml

With this change, the code coverage report should only be sent once to
the Scrutinizer CI service (after the build with PHP 5.6 has finished).
This fixes #1163.

send coverage report to Scrutinizer CI only once

---

Form/Extension/DisableCSRFExtension.php
Resources/config/forms.xml

See: https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form

Fix deprecated form.type_extension tag alias option usage

---

Form/Extension/DisableCSRFExtension.php
Resources/config/forms.xml

This BC for getExtendedType has to be included if the master branch is going to support 2.7 and up.

[master] csrf getExtendedType with BC for < 2.8

---

Controller/Annotations/Version.php
Resources/doc/format_listener.rst
Routing/Loader/Reader/RestActionReader.php
Routing/Loader/Reader/RestControllerReader.php
Tests/Fixtures/Controller/AnnotatedVersionUserController.php
Tests/Fixtures/Etalon/annotated_version_controller.yml
Tests/Routing/Loader/RestRouteLoaderTest.php

Makes it possible to set a route condition checking the matched version:
```
use FOS\RestBundle\Controller\Annotations\Version;
/**
* @Version("v2")
*/
class MyController
{
```
will add a condition to all routes, ie.:
```
my_route:
...
condition: "request.attributes.get('version') == 'v2'"
```

added version annotation

---

DependencyInjection/Compiler/FormatListenerRulesPass.php
Tests/DependencyInjection/Compiler/FormatListenerRulesPassTest.php

This pr fixes an error.
See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1179#issuecomment-149923127
>
Here is the debug output :
>
```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]
The service definition "fos_rest.exception_format_negotiator" does not exist.
>
Exception trace:
() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\ContainerBuilder.php:868
Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() at C:\Program Files\Wamp Server\www\Unanimita\API\vendor\friendsofsymfony\rest-bundle\DependencyInjection\Compiler\FormatListenerRulesPass.php:77
FOS\RestBundle\DependencyInjection\Compiler\FormatListenerRulesPass->addRule() at C:\Program Files\Wamp …
```

Fix an error

---

Routing/Loader/Reader/RestActionReader.php
Routing/Loader/Reader/RestControllerReader.php
Tests/Fixtures/Controller/AnnotatedVersionUserController.php
Tests/Fixtures/Etalon/annotated_version_controller.yml

This PR allows to define multiple versions for a single controller:
```php
<?php
use FOS\RestBundle\Controller\Annotations\Version;
/**
* @Version({"v1", "v2"})
* or
* @Version("v3")
*/
class Foo {}
```

Allows to define several versions

---

DependencyInjection/FOSRestExtension.php
Tests/DependencyInjection/FOSRestExtensionTest.php

I was having this problems to generate de cache using one zone:
Warning: substr() expects parameter 1 to be string, object given
With --no-debug:
PHP Warning:  strpos() expects parameter 1 to be string, object given in /home/r00t/Workspace/corporapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 563
PHP Warning:  ltrim() expects parameter 1 to be string, object given in /home/r00t/Workspace/corporapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 563
PHP Warning:  ltrim() expects parameter 1 to be string, object given in /home/r00t/Workspace/corporapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Dumper/PhpDumper.php on line 563
PHP Warning:  substr() expects parameter 1 to be …

Patched zone creations

---

Routing/Loader/Reader/RestActionReader.php
Tests/Fixtures/Controller/TypeHintedController.php
Tests/Routing/Loader/RestRouteLoaderTest.php
composer.json

I'm playing with symfony psr7 bridge and using `ServerRequestInterface` typehint instead of Symfony's `Request` in actions caused incorrect route generation. Collection routes get suffixed with `/{request}` param, item routes as well, when the `$request` param was the first.
This PR fixes that by adding `Psr\Http\Message\ServerRequestInterface` to ignored classed in `RestActionReader`. I also added a simple test case for PSR's and Symfony's request.

Ignoring PSR7 request typehint in route loader

---

Resources/doc/versioning.rst

It does not show correctly the part of the documentation of versioning, that does not show as block code

Solved a problem with the documentation

---

.travis.yml
DependencyInjection/Compiler/ExceptionWrapperHandlerPass.php
DependencyInjection/FOSRestExtension.php
EventListener/ParamFetcherListener.php
Form/Extension/DisableCSRFExtension.php
Routing/Loader/Reader/RestActionReader.php
Routing/Loader/Reader/RestControllerReader.php
Serializer/ExceptionWrapperSerializeHandler.php
Tests/Context/Adapter/ArrayContextAdapterTest.php
Tests/Context/Adapter/ChainContextAdapterTest.php
Tests/Context/Adapter/JMSContextAdapterTest.php
Tests/Context/ContextTest.php
Tests/Controller/Annotations/AbstractParamTest.php
Tests/DependencyInjection/Compiler/ConfigurationCheckPassTest.php
Tests/DependencyInjection/Compiler/FormatListenerRulesPassTest.php
Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php
Tests/DependencyInjection/FOSRestExtensionTest.php
Tests/EventListener/BodyListenerTest.php
Tests/FOSRestBundleTest.php
Tests/Request/ParamFetcherTest.php
Tests/Request/ParamReaderTest.php
Tests/Request/RequestBodyParamConverterTest.php
Tests/Routing/Loader/LoaderTest.php
Tests/Validator/ViolationFormatterTest.php
Tests/View/JsonpHandlerTest.php
Tests/View/ViewHandlerTest.php
composer.json

This PR change the minimum version of php required to use FOSRestBundle.
It also updates many class paths to the new syntax sugar ``Foo::class``

Bump minimum php version to 5.5

---

Resources/doc/param_fetcher_listener.rst

guess the plus got carried over from the other examples, not really important for the explanation of the feature, still it looked wrong

fix likely typo in param fetcher doc example

---

Normalizer/CamelKeysNormalizer.php
Normalizer/CamelKeysNormalizerWithLeadingUnderscore.php
Resources/config/body_listener.xml
Resources/doc/body_listener.rst
Tests/Normalizer/CamelKeysNormalizerTest.php

ie. leave '_username' unchanged
fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1009

ignore any number of leading underscores when converting from snake case to camel case

---

View/View.php

When creating a new instance using the 'static' keyword but the
docblock uses the class name, autocomplete can't figure out the late
static binding. Changing this to 'static' fixes this.

Change docblock return value to 'static'

---

DependencyInjection/FOSRestExtension.php
Tests/DependencyInjection/FOSRestExtensionTest.php

``fos_rest.converter.request_body`` is always touched even if it doesn't exist in ``loadSerializer``.
Fix #1268

Fix a bug in FOSRestExtension

---

Controller/ExceptionController.php
Decoder/ContainerDecoderProvider.php
DependencyInjection/FOSRestExtension.php
EventListener/ParamFetcherListener.php
EventListener/ViewResponseListener.php
Request/ParamFetcher.php
Request/RequestBodyParamConverter.php
Resources/config/body_listener.xml
Resources/config/exception_listener.xml
Resources/config/param_fetcher_listener.xml
Resources/config/request.xml
Resources/config/view.xml
Resources/config/view_response_listener.xml
Tests/DependencyInjection/FOSRestExtensionTest.php
Tests/EventListener/BodyListenerTest.php
Tests/EventListener/ParamFetcherListenerTest.php
Tests/EventListener/ViewResponseListenerTest.php
Tests/Request/ParamFetcherTest.php
Tests/View/JsonpHandlerTest.php
Tests/View/ViewHandlerTest.php
View/ViewHandler.php

Fork of #1171 on ``FOSRestBundle`` repository to make it easier to contribute to this PR.
> Injecting the container in your services is not a good practice. After this, there are only three classes left that rely on the container being injected: The ``RestRouteLoader`` class needs it to resolve controllers registered as services, the ``ParamFetcher`` class injects the container into container aware ``ParamInterface`` implementations, and the parent class of the ``ViewResponseListener`` uses the container.

stop injecting the container when possible

---

.travis.yml

We only need to cache downloaded packages but not metadata from Packagist.

update Composer cache directory on Travis CI

---

DependencyInjection/Compiler/TwigExceptionPass.php
Resources/config/exception_listener.xml

The controller resolver in the Symfony FrameworkBundle lazy loads
controllers as services. Thus, the Twig exception controller service
must be `public` and we must remove it in a compiler pass in case the
injected `templating.engine.twig` service definition does not exist.

make Twig exception controller service public

---

Resources/doc/empty-content-status-code.rst
Resources/doc/index.rst
Tests/View/ViewHandlerTest.php
Tests/View/ViewTest.php
View/View.php
View/ViewHandler.php

resolves #1278 and #1126 
the status code in *FOS\RestBundle\View\View* is null by default (on getResponse() null will be 200 in the response object).
If the code is null and the content is null, the emptyContentErrorCode will be used.
But if the status code is not null, the given status code will be used.

make status code configurable even if content is empty

---

Negotiation/FormatNegotiator.php
Tests/Negotiation/FormatNegotiatorTest.php

Hey!
When trying to perform request on an API without providing the `Accept` header, the fallback format is not used (if the matched rule defines priotities) and instead a `Negotiation\Exception\InvalidArgument` is thrown because the Negotiation library seems not supporting empty header in its 2.x version.

Fix fallback format with priorities

---

.travis.yml

Disabling Xdebug on Travis CI jobs that do not generate code coverage
reports speeds up builds significantly.

disable Xdebug on Travis CI when possible

---

Serializer/JMSSerializerAdapter.php
Serializer/SymfonySerializerAdapter.php

The serializers are marked lazy, but defined as final. This causes an
exception being thrown when de container is initialized since it tries
to create a proxy, but fails because the classes are final.
Fixes#1325

Serializer adapters no longer final

---

Controller/Annotations/Copy.php
Controller/Annotations/Lock.php
Controller/Annotations/Mkcol.php
Controller/Annotations/Move.php
Controller/Annotations/PropFind.php
Controller/Annotations/PropPatch.php
Controller/Annotations/Unlock.php
Resources/doc/5-automatic-route-generation_single-restful-controller.rst
Resources/doc/annotations-reference.rst
Routing/Loader/Reader/RestActionReader.php
Routing/RestRouteCollection.php
Tests/Fixtures/Controller/AnnotatedUsersController.php
Tests/Fixtures/Controller/ArticleController.php
Tests/Fixtures/Controller/OrdersController.php
Tests/Fixtures/Controller/UsersController.php
Tests/Fixtures/Etalon/annotated_users_controller.yml
Tests/Fixtures/Etalon/prefixed_users_collection.yml
Tests/Fixtures/Etalon/resource_controller.yml
Tests/Fixtures/Etalon/users_collection.yml
Tests/Fixtures/Etalon/users_controller.yml
Tests/Routing/Loader/RestRouteLoaderTest.php
UPGRADING.md
composer.json

this pr aims to provide support for the http methods introduced in the RFC-2518 (e.g. LOCK/UNLOCK or MOVE)
**ToDo**

Compatibility for RFC-2518

---

Controller/Annotations/Copy.php
Controller/Annotations/Lock.php
Controller/Annotations/Mkcol.php
Controller/Annotations/Move.php
Controller/Annotations/PropFind.php
Controller/Annotations/PropPatch.php
Controller/Annotations/Unlock.php
Resources/doc/5-automatic-route-generation_single-restful-controller.rst
Resources/doc/annotations-reference.rst
Routing/Loader/Reader/RestActionReader.php
Tests/Fixtures/Controller/AnnotatedUsersController.php
Tests/Fixtures/Controller/OrdersController.php
Tests/Fixtures/Controller/UsersController.php
Tests/Fixtures/Etalon/annotated_users_controller.yml
Tests/Fixtures/Etalon/users_controller.yml
Tests/Routing/Loader/RestRouteLoaderTest.php

This backports the backwards compatible parts of #1314 to the `1.8` branch.

backport RFC-2518 annotations

---

.travis.yml
DependencyInjection/Configuration.php
DependencyInjection/FOSRestExtension.php
EventListener/MimeTypeListener.php
Negotiation/FormatNegotiator.php
Resources/config/exception_listener.xml
Resources/config/format_listener.xml
Resources/doc/format_listener.rst
Tests/Functional/app/Version/config.yml
Tests/Negotiation/FormatNegotiatorTest.php
UPGRADING.md

Re-add the ability to transform automatically most common mime types.
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1149#discussion-diff-41261255

[FormatNegotiator] Re-add the ability to transform automatically most common mime types when using symfony 3.1

---

EventListener/AccessDeniedListener.php
Resources/config/access_denied_listener.xml
Resources/doc/3-listener-support.rst
UPGRADING.md

See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1356#issuecomment-190932403
This PR makes the AccessDeniedListener simpler and let the others listeners render the response.

Allow to customize deeper the AccessDeniedListener

---

DependencyInjection/Compiler/ConfigurationCheckPass.php
Tests/DependencyInjection/Compiler/ConfigurationCheckPassTest.php
Tests/Functional/app/Configuration/config.yml

People doesn't seem to read the upgrading file so it's probably better to throw an exception when their configuration won't work.
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1381

Throw an exception an exception when the SensioFrameworkExtraBundle is wrongly configured

---

Resources/config/routing.xml
Routing/Loader/DirectoryRouteLoader.php
Tests/Functional/Bundle/TestBundle/Controller/Api/CommentController.php
Tests/Functional/Bundle/TestBundle/Controller/Api/PostController.php
Tests/Functional/RoutingTest.php
Tests/Functional/app/Routing/bundles.php
Tests/Functional/app/Routing/config.yml
Tests/Functional/app/Routing/routing.yml
Tests/Routing/Loader/DirectoryRouteLoaderTest.php

This fixes support for the bundle shortcut notation when loading routes from a directory (fixes #1377).

fix loading route directory resources

---

UPGRADING.md

The change was introduced in #1308. Since #1382 the `ConfigurationCheckPass` will also throw an exception.

document view annotation requirement for upgrades

---

DependencyInjection/Configuration.php
DependencyInjection/FOSRestExtension.php
Resources/config/exception_listener.xml
Tests/DependencyInjection/FOSRestExtensionTest.php
Tests/Functional/Bundle/TestBundle/Controller/SerializerErrorController.php
Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml
Tests/Functional/SerializerErrorTest.php
Tests/Functional/app/Debug/bundles.php
Tests/Functional/app/Debug/config.yml

In order to be able manually enable/disable exception in error response.
Now kernel.debug value is used and it is not useful in some cases.
For example in functional test, thou it is run in debug mode, be able to check error response as it would be in prod environment (without exception).

Add fos_rest.exception.show_exceptions config param

---

EventListener/ExceptionListener.php

Fixes missing zone check as mentioned in #1402

Adds zone support to ExceptionListener

---

Controller/Annotations/AbstractScalarParam.php
Tests/Controller/Annotations/AbstractScalarParamTest.php

When upgrading to [2.0.0-BETA2](https://github.com/FriendsOfSymfony/FOSRestBundle/releases/tag/), we ran into cases where we had this kind of annotation:
```php
/*
* @QueryParam(name="filter", map=true, nullable=true)
*/
```
This broke as of #1191 (I believe) because using `Constraints\All` requires at least one constraint. Simple fix is to check to see if any actual constraints were specified.
```bash
phpunit --filter ParamFetcherTest
```
This may be considered user error, but we also rely on the `map` property (previously `array`) to indicate that we expect to treat this parameter as an array. This is a case where `be liberal in what you accept, conservative in what you emit` informs my opinion that we should let consumers of this code use the `map=true` option liberally.
Tangential …

Fix QueryParam map with no constraints breaking

---

DependencyInjection/Compiler/TwigExceptionPass.php
EventListener/ExceptionListener.php
Tests/Functional/ExceptionListenerTest.php
Tests/Functional/app/ExceptionListener/bundles.php
Tests/Functional/app/ExceptionListener/config.yml

@jovobe discovered that core Symfony exception listener was removed when the one from the FOSRestBundle was registered. This leads to errors when an exception is thrown for a request that does not match a configured REST zone meaning that the exception is entirely ignored by the exception handling process.

fall back to core Symfony exception listener outside configured REST zones

---

Context/Context.php
Tests/Context/ContextTest.php

This puts the `Context` class in `1.8` and `2.0` in sync again.

backport #1427

---

Normalizer/CamelKeysNormalizer.php
Tests/Normalizer/CamelKeysNormalizerTest.php

In #1267, a new normalizer class was introduced that ignores underscores
when converting snake case to camel case. However, the same change was
made to the base class. This means that both classes act in exactly the
same way. Furthermore, this change was a BC break as the behavior of the
base normalizer class was changed without fixing an actual bug.

ignore leading underscores in base normalizer

---

Resources/doc/2-the-view-layer.rst
Resources/doc/4-exception-controller-support.rst
Resources/doc/5-automatic-route-generation_single-restful-controller.rst
Resources/doc/6-automatic-route-generation_multiple-restful-controllers.rst
Resources/doc/param_fetcher_listener.rst
Resources/doc/view_response_listener.rst

Added namespace `AppBundle\Controller` to all documentation examples that show a Controller class, according to symfony standards for documentation.
Closes #1266.

Add namespace in documentation examples that show a Controller class

---

CHANGELOG.md
Resources/config/view.xml
Tests/DependencyInjection/FOSRestExtensionTest.php

This basically backports #1365 to FOSRestBundle 1.7.

fixed groups to default to an empty collection

---

Controller/Annotations/Param.php

The new `ParamInterface` requires implementing classes to provide the
body of the `getValue()` method. This adds an empty implementation to
the `Param` class to prevent BC breaks for existing classes that extend
the `Param` class.

[#1463] add empty implementation for required method

---

Controller/ExceptionController.php

Without the type hint we can also support objects implementing the
\Throwable interface when using PHP 7.

remove \Exception type hint

---

Resources/config/exception_listener.xml

This makes it easier for custom normalizers to be executed before the
one from FOSRestBundle as one would not need to specify a priority
anymore.
This fixes #1488.

decrease exception normalizer priority

---

Context/Context.php
EventListener/ViewResponseListener.php
Request/RequestBodyParamConverter.php
Serializer/JMSSerializerAdapter.php
Serializer/SymfonySerializerAdapter.php
Tests/Context/ContextTest.php
Tests/EventListener/ViewResponseListenerTest.php
Tests/Request/RequestBodyParamConverterTest.php

Both serializers don't allow to define maxDepth at runtime so it shouldn't have been called this way...
I'm targeting master as this may break apps using 2.0.

Deprecate the maxDepth context attribute in favor of enableMaxDepth

---

composer.json

jms serializser 1.3 changed the default value of `Context::serializeNull`
ref: https://github.com/schmittjoh/serializer/pull/317

fix compatibility with jms serializer 1.3.

---

Exception/InvalidParameterException.php
Tests/Request/ParamFetcherTest.php

Handle invalid param exception when invalid value is not scalar

---

Resources/doc/annotations-reference.rst

I noticed this while doing annotations based off the docs. It looks like the `array` property for the annotation `QueryParam` and `RequestParam` was changed to `map` a while ago.

Update the annotation doc to change array to map.

---

DependencyInjection/Configuration.php
DependencyInjection/FOSRestExtension.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/FOSRestExtensionTest.php

According to [configuration](http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html) we can use constants from Symfony Response class as a value for `exception.codes` configuration section.
However when the bundle is configured in such a way, the constant is not converted into corresponding http status code what leads to error during run time. This PR fixes incorrect behavior and converts constant to value during configuration normalization.

#1571 Fixed using Response constants in exception codes configuration

---

.travis.yml

Symfony 3.0 is not forward-compatible with Twig 2.0 (it references Twig
extensions by their name instead of the extension's FQCN) and won't be
updated anymore as it already reached end of maintenance. This currently
lets our Travis CI builds fail.

drop the build job using Symfony 3.0

---

composer.json

Instead of relying on the Symfony FrameworkBundle to pull in all our
needed dependencies, we should explicitly list all of them. This will
ensure that nothing breaks when the FrameworkBundle stops depending on
some optional dependencies (which was done recently).

explicitly list all required packages

---

Request/RequestBodyParamConverter.php
Tests/Request/RequestBodyParamConverterTest.php

I have a requirement that the RequestBodyParamConverter doesnt perform the validation, so my controller action can calculate which validation groups are required and do it itself.
Seems to me like its logical that this is configurable on ParamConverter.

Option to skip RequestBody validation

---

Resources/doc/view_response_listener.rst

Using View for both creating View and as annotations cause error 
`The class \"FOS\\RestBundle\\View\\View\" is not annotated with @Annotation`
Fixed to use `View` for creating object and `ViewAnnotation` as annotation

[Doc] Fix invalid usuage of annitation

---

Resources/doc/3-listener-support.rst

@xabbuh is this correct?
right now the section isn't being listed http://symfony.com/doc/current/bundles/FOSRestBundle/3-listener-support.html#security-exception-listener

correct the markup for the zone listener docs

---

Resources/doc/view_response_listener.rst

Replaced View::setSerializationContext call in example with View::setContext as previous method does not exist anymore

View::setSerializationContext inexistant

---

Resources/doc/param_fetcher_listener.rst

This is an image so the correct mime type would be "image/jpeg" or "image/something".

Bad mime type

---

Resources/config/view.xml
Tests/View/ViewHandlerTest.php
View/ViewHandler.php

Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1652

Allow disabling the templating component

---

Negotiation/FormatNegotiator.php
Tests/Negotiation/FormatNegotiatorTest.php

Fixes issue #1661 
When prefer_extension is set, the Accept header will be prepended to instead of appended to. This ensures that the Accept header cannot override the qvalue of the extension mime-type, like in this scenario:
```
Location: http://example.com/file.json
Accept: text/html, application/json; q=0.1
```
If no mime-type can be found for the extension, the Accept header will not be modified.
Added unit tests for prefer_extension to ensure content negotiation remains predictable.

Fixed prefer_extension content negotiation

---

Request/RequestBodyParamConverter.php
Tests/Functional/Bundle/TestBundle/Controller/RequestBodyParamConverterController.php
Tests/Request/RequestBodyParamConverterTest.php

Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1659
When a parameter is not a class registered in doctrine, the `RequestBodyParamConverter` can be reached without being explicitly asked which is not expected (imo at least).

[RequestBodyParamConverter] Force being explicit

---

Routing/RestRouteCollection.php
Tests/Fixtures/Controller/OrdersController.php

The regex pattern in RestRouteCollection::all() was including the whitespace and the comment, causing it to fail against all route names (thinking they are all custom). This broke the sorting that allowed routes like `get_user` to be defined before routes like `new_user` and `remove_user` without breaking them. 
This bug was introduced between 1.8 and 2.0, when the pattern was pulled out of the foreach loop.

Fixed regular expression pattern used to detect custom routes in RestRouteCollection.

---

Resources/config/serializer.xml
Serializer/JMSSerializerAdapter.php
Tests/Serializer/JMSSerializerAdapterTest.php
Tests/View/ViewHandlerTest.php
composer.json

As of jms/serializer 1.4.0 (and jms/serializer-bundle 1.2.0) is possible to configure the default context via services ([doc](http://jmsyst.com/libs/serializer/master/configuration#setting-a-default-serializationcontext-factory)).
This PR improves the integration with FOS Rest and JMS serializer
(I have also added some extra tests for the `JMSSerializerAdapter` class)

Use JMS Serializer Context Factories to create new contextes

---

Serializer/Normalizer/ExceptionHandler.php

without this check, some of our error handling fails with the invalid access to the non-existing array key.

check if templateData contains the field status_code

---

DependencyInjection/Compiler/FormatListenerRulesPass.php
DependencyInjection/FOSRestExtension.php
Tests/DependencyInjection/FOSRestExtensionTest.php

`ChildDefinition` was introduced in Symfony 3.2 and replaces the `DefinitionDecorator` class which will be removed in Symfony 4.0.

use ChildDefinition when possible

---

DependencyInjection/Configuration.php
Resources/doc/configuration-reference.rst

I noticed that for exception.service configuration option was not added with [this commit](https://github.com/FriendsOfSymfony/FOSRestBundle/commit/a3ee6d7c4427d569d577e717ab8dccc1a857abbd). Without this option [FOSRestExtension.php#L328](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/DependencyInjection/FOSRestExtension.php#L328) is unreachable and default ExceptionListener is always registered as an event subscriber.
If there is an actual reason why this listener should always be active, code block in FOSRestExtension should be removed.

add fos_rest.exception.service to configuration

---

.travis.yml

* drop builds for no longer maintained Symfony versions
* do not run tests on HHVM anymore
* remove generic PHP 5.5 and 7.0 jobs (they are already covered by
other explicit matrix entries)

shrink the build matrix

---

Resources/config/exception_listener.xml

With Symfony 4.0+, services will be private by default if not configured
differently. A controller that is registered as a service must be public
to allow the resolver to properly retrieve the controller from the
service container.

make the exception controller service public

---

Routing/Loader/DirectoryRouteLoader.php

Symfony Flex introduced a new notation for routes resources:
```
controllers:
resource: "../src/Controller"
```
The current implementation of `DirecotryRouteLoader` supports only @ notation to locate a resource by file locator. That PR fix it for Symfony Flex notation.

Support dot notation for resources in symfony flex

---

Tests/Functional/app/config/default.yml
phpunit.xml.dist

The change done in #1797 had the disadvantage that it silenced all
log entries. Using the `SHELL_VERBOSITY` env var allows to define a
level for which log entries should still be shown.

do not silence error logs

---

.travis.yml

So the output will be folded by default by Travis CI and does not
clutter the tests' output.

install PhpUnitBridge dependencies before running tests

---

Tests/Context/ContextTest.php
Tests/Controller/Annotations/AbstractParamTest.php
Tests/Controller/Annotations/AbstractScalarParamTest.php
Tests/Decoder/JsonToFormDecoderTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/FOSRestExtensionTest.php
Tests/EventListener/ViewResponseListenerTest.php
Tests/Request/RequestBodyParamConverterTest.php
Tests/Routing/Loader/RestRouteLoaderTest.php
Tests/Routing/Loader/RestXmlCollectionLoaderTest.php
Tests/Routing/Loader/RestYamlCollectionLoaderTest.php

I've refactored some tests using:
- `assertCount` instead of `count` function;
- `assertInstanceOf` instead of `instanceof` operator;
- `assertArrayHasKey` instead of `isset` function;
- `assertNull` instead of comparison with `null` keyword;
- `assertFalse` instead of comparison with `false` keyword;
- `assertTrue` instead of comparison with `true` keyword;
- `assertInternalType` instead of `is_*` functions;
- `assertSame` instead of strict comparisons.

Refactoring tests

---

FOSRestBundle.php
Tests/Functional/DependencyInjectionTest.php

If the `JMSHandlersPass` is registered as a `TYPE_REMOVE` pass, the
definitions it depends on may already be removed before by the built-in
`RemoveUnusedDefinitionsPass`. That compiler pass removes private
services that are not referenced. This becomes critical, for example,
when running a Symfony 4 based application where services will be
private by default.
This is the first PR of a series of changes we need to do to fully solve
#1790.

tests for definitions before they might be removed

---

DependencyInjection/FOSRestExtension.php
Tests/DependencyInjection/FOSRestExtensionTest.php

The alias will be fetched from the container when using the built-in
FOSRestController class. Thus, we must ensure that it can still be
located when using Symfony 4.0 or higher.

make the view handler alias public

---

FOSRestBundle.php

This does not solve the root issue of #1812. However, it will throw a meaningful error during container compilation so that users can find out how to work around (by enabling TwigBundle).

run checks after SensioFrameworkExtraBundle

---

DependencyInjection/Compiler/HandlerRegistryDecorationPass.php
DependencyInjection/Compiler/JMSHandlersPass.php
FOSRestBundle.php

This works around the fact that custom handlers are processed in
JMSSerializerBundle after Symfony's DecoratorServicePass has been
executed (which means that we cannot use proper service decoration).
The old code still used to work on Symfony 2.x applications where
FOSRestBundle was registered after JMSSerializerBundle. In those cases,
custom handlers were processed before the handler registry was replaced
by the compiler pass coming from FOSRestBundle.
More recent Symfony applications have not been affected by this bug as
the compiler pass priority would have ensured the correct order in which
the passes would have been executed.

manually decorate the core JMS handler registry

---

DependencyInjection/Configuration.php

fix error introduced with https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1912
Because of it `body_converter.validate` is always `NULL`

Fix failing tests

---

CHANGELOG.md
Controller/Annotations/Route.php
Resources/doc/annotations-reference.rst

The @Route annotations is in a different namespace for symfony 4. I guess this will break compatibility with symfony < 4, so I'm not sure what is the best way to handle this. But currently, this fixes
`In Route.php line 21:
Attempted to load class "Route" from namespace "Sensio\Bundle\FrameworkExtraBundle\Configuration".                                                      
Did you forget a "use" statement for e.g. "Symfony\Component\Routing\Annotation\Route" or "Symfony\Component\Routing\Route"?`
for me.

Fixed use statement for symfony 4 compatibility

---

Routing/Loader/Reader/RestActionReader.php
Tests/Fixtures/Controller/ParamConverterController.php
Tests/Routing/Loader/RestRouteLoaderTest.php

When fetching a list of function parameters from a controller action
for use as URL parameters, check for the @ParamConverter
annotation. If a parameter has the annotation with the
"fos_rest.request_body" converter, then ignore it and do not include
it in the list of parameters (thus removing it from the URL).
This allows automatic route generation and ParamConverter to co-exist,
as otherwise a parameter that is expected to be derived from the body
would also be included as a URL parameter, requiring the developer to
manually specify the route.
fixes #1198

fix route generator not ignoring body param converters

---

Request/ParameterBag.php
composer.json

\FOS\RestBundle\Request\ParameterBag has a dependency to
\Doctrine\Common\Util\ClassUtils which originates from doctrine/common
which in turn a dependency of sensio/framework-extra-bundle but this is
declared as a dev-dependency. This causes an fatal error with the
message 'Class 'Doctrine\Common\Util\ClassUtils' not found'.
Fixes#259

Fix dependency to sensio/framework-extra-bundle

---

DependencyInjection/FOSRestExtension.php
Resources/config/view.xml
View/ViewHandler.php

ViewHandler keeps an internal state of the variables
- exclusionStrategyGroups
- exclusionStrategyVersion
- serializeNullStrategy
which causes inconsistencies when used with [PHP-PM](https://github.com/php-pm/php-pm). This PR fixes this by utilizing the "kernel.reset" tag introduced for this purpose in https://github.com/symfony/symfony/issues/23984 to reset the state of these variables after each request.

Reset internal state of ViewHandler at the end of request

---

Util/ResolverTrait.php

There was 3 variables for 2 placeholders

Fix typo in RuntimeException

---

Routing/Loader/DirectoryRouteLoader.php

Loading routes from all controllers in a directory:
---
api:
resource: "@AppBundle/Controller/"
type: rest
---
The controllers are not loaded in order and this generates different routes lists for different deployments.
This produces different FOSJsRoutingBundle static javascript file for each deploy, using "fos:js-routing:dump".
When combining javascripts files using hash based file name, it will generate different file names per deploy, affecting multiple equal deploys behind a load balancer, trying to load a javascript file that only exists in one of the servers.
My change is to order the controllers by file name, like symfony is doing loading its controllers from a directory:
Symfony\Component\Routing\Loader\AnnotationDirectoryLoader
---
usort($files, function (\SplFileInfo $a, …

Ordering controllers by filename before load their routes

---

DependencyInjection/Compiler/HandlerRegistryDecorationPass.php
Serializer/JMSHandlerRegistryV2.php
Serializer/JMSSerializerAdapter.php
Serializer/Normalizer/ExceptionHandler.php
Serializer/Normalizer/FormErrorHandler.php
Tests/Functional/DependencyInjectionTest.php
Tests/Serializer/JMSSerializerAdapterTest.php
composer.json

This introduces the changes for supporting the upcoming jms/serializer 2.0 release
Some changes in composer.json and travisci are will not be necessary when serializer v1.13 will be released

jms/serializer 2.0 compatibility

---

composer.json

~~`GraphNavigatorInterface` has been introduced in JMS Serializer v1.12.0. We should use `GraphNavigator` instead to maintain backward compatibility with v1.11.0 and lower.~~
#1899 breaks compatibility with `jms/serializer <1.13.0` by using:
- `JMS\Serializer\GraphNavigatorInterface` (>=1.12)
- `JMS\Serializer\Context::hasAttribute()` (>=1.13)
- `JMS\Serializer\Context::getAttribute()` (>=1.13)
However, it is still possible to install older version of `jms/serializer` together with FOSRestBundle. This PR fixes it by updating a `conflict` constraint.

Drop jms/serializer <1.13

---

Controller/Annotations/AbstractScalarParam.php
Tests/Controller/Annotations/AbstractScalarParamTest.php

Currently we have some problems with `map` options.
In fact it is with `map` and anothers options like `nullable` or `notBlank`.

Fix problems with map option

---

Controller/Annotations/AbstractScalarParam.php
Tests/Controller/Annotations/AbstractScalarParamTest.php

Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1769/files/da8d1ff7d91e5e178022b82a206eacf9b604f3b1#r231027007

Apply NotBlank only to the whole array

---

Request/ParamFetcher.php
Tests/Request/ParamFetcherTest.php

Depreciate null validator on ParamFetcher constructor to remove runtime check (see below) at the next major version.
https://github.com/FriendsOfSymfony/FOSRestBundle/blob/a5fc73b84bdb2f0fdf58a717b322ceb6997f7bf3/Request/ParamFetcher.php#L137

Depreciate null validator on ParamFetcher constructor

---

DependencyInjection/FOSRestExtension.php
Request/ParamFetcher.php

Related to #1843 
It seems symfony/validator (currently in composer dev requirements) should be in requirements instead, since at least the `NotNull` constraint is used here: https://github.com/FriendsOfSymfony/FOSRestBundle/blob/ee844447be0fe6fbe99ed678f70db342a60a4ccc/Controller/Annotations/AbstractParam.php#L75

Throw meaningful exception when using ParamFetcher without symfony/validator installed

---

Resources/doc/param_fetcher_listener.rst

use statement is required to use Symfony constraints in the requirements annotations

[DOC] Adds missing use statement in order to constraints

---

Routing/Loader/Reader/RestActionReader.php
Tests/Fixtures/Controller/UsersController.php
Tests/Fixtures/Etalon/users_controller.yml
Tests/Routing/Loader/RestRouteLoaderTest.php

Route creation relies on controller actions' method arguments for a couple of things.. as such, some commonly injected arguments [are already filtered](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/e1f91266ca37e423dfae9ec4e641b247fdb2915d/Routing/Loader/Reader/RestActionReader.php#L530-L536). 
This PR includes two more commonly injected interfaces to the exclusion list, as seen in the [list of Symfony's built-in arguments resolvers](https://symfony.com/doc/3.4/controller/argument_value_resolver.html#built-in-value-resolvers).
Route name and path can be easily overwritten so this PR is usually easily workaround-able, but there's still one feature which relies on action arguments: controller hierarchy.
It needs at least one method [having exactly one …

Ignore SessionInterface and UserInterface controller action arguments

---

Tests/EventListener/ViewResponseListenerTest.php
Tests/View/JsonpHandlerTest.php
Tests/View/ViewHandlerTest.php

Because the Templating Component has been deprecated.

Use Twig engine for unit tests

---

DependencyInjection/Compiler/ConfigurationCheckPass.php
Tests/Functional/ConfigurationTest.php
Tests/Functional/app/AppKernel.php
Tests/Functional/app/Configuration/config.yml
Tests/Functional/app/ConfigurationWithTwig/bundles.php
Tests/Functional/app/ConfigurationWithTwig/config.yml
Tests/Functional/app/ConfigurationWithTwig/routing.yml
Tests/Functional/app/ConfigurationWithTwig/security.php

Currently if `symfony/templating` is not installed the following error could happen:
> An instance of Symfony\Component\Templating\EngineInterface must be injected in FOS\RestBundle\View\ViewHandler to render templates.
thats because templating is set as default value. If templating is not available but twig it should use twig instead.

Use twig as templating engine when available

---

Tests/Functional/ConfigurationTest.php
Tests/Functional/ExceptionListenerTest.php
Tests/Functional/RoutingTest.php
Tests/Functional/VersionTest.php
composer.json

#2066, #2067, and #2068 should have actually been merged into `2.x`

backport fixes from master

---

Controller/ExceptionController.php
Util/ExceptionValueMap.php

I've this problem on my projet
```Uncaught Error: Argument 1 passed to FOS\\RestBundle\\Controller\\ExceptionController::getStatusCode() must be an instance of Exception, instance of Error given, called in /var/www/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 68```
To solve this i just change two files.

Fix throwable error on exception controller

---

Resources/config/view.xml

Changed `FOS\RestBundle\View\ViewHandlerInterface` to be an alias of "fos_rest.view_handler" instead of "fos_rest.view_handler.default". So in case if a custom ViewHandler has been configured under "fos_rest.service.view_handler" it will be used. Before this change, the used ViewHandler of Controller extending the `AbstractFOSRestController` would always have been pointing to `fos_rest.view_handler.default` because the service subscriber definition is `$subscribedServices['fos_rest.view_handler'] = ViewHandlerInterface::class;`.
This should fix #2029

Fixed used alias for "FOS\RestBundle\View\ViewHandlerInterface"

---

Serializer/Normalizer/AbstractExceptionNormalizer.php
Serializer/Normalizer/ExceptionHandler.php
Serializer/Normalizer/ExceptionNormalizer.php

handle all Throwable instances during serialization

---

.travis.yml
Controller/ExceptionController.php
EventListener/ExceptionListener.php
Resources/config/exception_listener.xml

Part of https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2108
* Typehinting `\Throwable` in the exception controller allows us to get rid of the argument controller logic, which is done by the ErrorListener if necessary

decorate the exception_listener - simplification

---

Routing/Loader/Reader/RestActionReader.php

allow ignored classes to be set in the rest action reader
fixes #2090

get and set ignored classes

---

Serializer/JMSSerializerAdapter.php
Tests/Context/ContextTest.php
Tests/Serializer/JMSSerializerAdapterTest.php

JMS Serializer is configured with max depth checking enabled when method `disableMaxDepth` is called in `FOS\RestBundle\Context\Context`.
This PR fixes the behaviour to actually configure serializer without max depth checking enabled in this scenario.

Fixed explicit disabling of serializer max depth checks

---

Serializer/Normalizer/ExceptionHandler.php

In #2126 this was accidently added to a protected function which could be overwritten.

Remove accidentally added return type from ExceptionHandler

---

composer.json

This is not needed anymore and not specific to rest-bundle but applies to symfony/routing in general when using a "condition" option.

remove expression-language suggest dependency

---

DependencyInjection/Compiler/TwigExceptionPass.php
Tests/Functional/app/RequestBodyParamConverterTwigBundle/config.yml

By default in symfony 4.4 the older exception controller is used so the error handler component is not used. If the exceptionListener is disabled the newer ErrorController need to be used else the mapping configuraiton and listeners don't work.
This would fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/2167#issuecomment-619902695 where on `prefer-lowest` and disabled `exception_listener` the error handler is not called and so the exception not correctly serialized

Throw exception for false combination of twig exception controller and exception_listener configuration

---

EventListener/AccessDeniedListener.php

This PR exprovides an alternative fix for https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1692
I tried to decorate the security component exception listener but it does not seem possible since the Firewall context has a typehint on the class (not an interface) on the exception listener (https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/SecurityBundle/Security/FirewallContext.php#L30) but the class is also marked as `@final` (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L43). As such the fix is essentially a hack by not pass the previous exception to prevent the core listener from doing anything.
open questions

remove previous exception, add tests for access denied listener

---

composer.json

In the 3.0 there seems no longer a need to require `Symfony\Component\Debug`.

Remove requirement to symfony/debug

---

Tests/Functional/AccessDeniedListenerTest.php
Tests/Functional/Bundle/TestBundle/Controller/Api/CommentController.php
Tests/Functional/Bundle/TestBundle/Entity/User.php
Tests/Functional/Bundle/TestBundle/Security/ApiTokenAuthenticator.php
Tests/Functional/app/AccessDeniedListener/config.yml
Tests/Functional/app/AccessDeniedListener/routing.yml
Tests/Functional/app/AccessDeniedListener/security.php

core already seems to do all the right things when using basic auth and/or json_login. so at least for 3.0, imho we should just remove the AccessDeniedListener and tell people to use `json_login` or adapt whatever custom solution they have.
however when using a custom guard authenticator it does not work properly out of the box unless one enables the the AccessDeniedListener and only with the removed `$exception` propagation done in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2109
that being said an alternative and likely cleaner approach in place of the AccessDeniedListener would be to offer a default implementation for a failure handler. so maybe for 3.0 this is what should be done? ie. drop AccessDeniedListener and add a failure handler? then we avoid even going into the …

make sure tests fail without access denied listener

---

DependencyInjection/Configuration.php
Resources/config/routing.xml

While trying to add support for FOSRestBundle 3.x to NelmioApiDocBundle, I found a few deprecations that could be improved:
- the deprecations from the routing services don't specify how to solve them, I added a reference to a config field
- deprecations of suboptions of `fos_rest.exception` even if `exception` is not enabled. I solved it by using `validate` instead of `defaultValue` + `beforeNormalization` at the level of `exception`.

Improve deprecations DX

---

Request/RequestBodyParamConverter.php
Tests/Request/RequestBodyParamConverterTest.php

```
Argument 3 passed to FOS\RestBundle\Serializer\JMSSerializerAdapter::deserialize() must be of the type string, null given
```

Fix requests without content type
