FriendsOfSymfony/FOSRestBundle

DependencyInjection/Compiler/SerializerConfigurationPass.php, DependencyInjection/FOSRestExtension.php, FOSRestBundle.php, Resources/doc/1-setting_up_the_bundle.rst, Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php, Tests/DependencyInjection/FOSRestExtensionTest.php, Tests/FOSRestBundleTest.php
follow up for https://github.com/FriendsOfSymfony/FOSRestBundle/pull/875
=> Automatically fallback to the core serializer if available

Routing/Loader/Reader/RestActionReader.php, Tests/Fixtures/Controller/ArticleController.php, Tests/Fixtures/Etalon/resource_controller.yml
fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/911
=> fixed handling of OPTIONS in route generation

Request/AbstractRequestBodyParamConverter.php, Request/ParamFetcher.php
@alekitto .. I took the liberty of opening a PR for you. it seems like you are working on an earlier branch of master, so you will need to rebase your branch.
fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/846
=> 2.5 validator API compatibility

README.md
waiting on the symfony.com update
fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/931
=> point to symfony.com for the docs

DependencyInjection/FOSRestExtension.php
This PR breaks the loading into different sections which are easier to read.
=> [DependencyInjection] Cleaned the extension

Controller/ExceptionController.php
fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/946
=> remove format parameter in ExceptionController::showAction()

Resources/config/request_body_param_converter.xml
=> fix request body param converter service config

Request/ParamFetcher.php, Tests/Request/ParamFetcherTest.php
Fixes FriendsOfSymfony/FOSRestBundle#960
=> [QueryParam] Nullable array with validation

EventListener/BodyListener.php, Tests/EventListener/BodyListenerTest.php
Fix for issue https://github.com/FriendsOfSymfony/FOSRestBundle/issues/976
=> Fixed array normalization for form post

Resources/doc/2-the-view-layer.rst
See also https://github.com/symfony/symfony-docs/issues/5151#issuecomment-89974092.
=> Add versionadded directive for setTemplateData

composer.json
follow up for https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1007
=> fix conflict to just list the validator

Controller/ExceptionController.php
should fix #958
TwigBundle PreviewErrorPage controller set the ```showException``` attribute to ```false``` in the subrequest.
Use the attribute if present and fallback to kernel debug flag to maintain BC.
=> don't break TwigBundle error page preview

DependencyInjection/Configuration.php, Tests/DependencyInjection/FOSRestExtensionTest.php
https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1020
=> includes #1020 as well as a test

Resources/doc/3-listener-support.rst, Resources/doc/body_listener.rst, Resources/doc/format_listener.rst, Resources/doc/index.rst, Resources/doc/param_fetcher_listener.rst, Resources/doc/request_body_converter_listener.rst, Resources/doc/view_response_listener.rst
can you look over this and tell me if it makes sense?
@WouterJ @weaverryan @javiereguiluz
=> split out all longer listener sections into their own document

Resources/doc/configuration-reference.rst
Spaces needed, code block not rendering
=> Fix code block

Resources/doc/format_listener.rst
I had a quite hard time to collect informations and make working the version functionality of the bundle.
I think it requires more detailed informations.
Here is my proposal, feel free to retouch my input to better english / informations :)
=> Adding information for version functionality

.travis.yml
* Symfony 2.7 is stable
* add build for Symfony 2.8.x@dev
=> update Symfony versions used on Travis

Response/AllowedMethodsLoader/AllowedMethodsRouterLoader.php
=> handle deprecation of ConfigCache::__toString()

DependencyInjection/Compiler/CsrfExtensionPass.php, FOSRestBundle.php, Form/Extension/DisableCSRFExtension.php, Resources/config/forms.xml, Tests/FOSRestBundleTest.php
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1063
=> Updated DisableCSRFExtension for 2.7+

Controller/Annotations/Route.php, Tests/Fixtures/Controller/AnnotatedConditionalUsersController.php, Tests/Fixtures/Controller/AnnotatedUsersController.php, Tests/Fixtures/Etalon/annotated_conditional_controller.yml, Tests/Fixtures/Etalon/annotated_users_controller.yml
supersedes https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1067
=> fix for regression with handling of Route annotations setting methods attribute in 1.7.0

Resources/doc/view_response_listener.rst
Added instructions about how to set a controller action setting template data not for serialization.
=> Adding details how to use setTemplateData when @View() annotation #1078

Tests/EventListener/ViewResponseListenerTest.php
Fixes #1088; test suite now passes.
=> Fixing broken test due to FrameworkExtraBundle change.

Resources/doc/1-setting_up_the_bundle.rst
=> Updated serializer configuration in setup

Controller/ExceptionController.php, Decoder/DecoderInterface.php, EventListener/FormatListener.php, EventListener/ParamFetcherListener.php
This PR fix several issues reported by Scrutinizer.
=> Fix several scrutinizer issues

EventListener/BodyListener.php
https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1108
=> Use empty function instead of equal to null for DELETE request (nginx compatibility)

Resources/doc/2-the-view-layer.rst
This patch fixes some small typos in `2-the-view-layer.rst`.
=> Fix view layer docs

composer.json
The stable release [is now a thing](https://github.com/willdurand/Negotiation/releases/tag/v2.0.0).
=> use stable release of willdurand/negotiation

.travis.yml, Controller/ExceptionController.php, Request/AbstractRequestBodyParamConverter.php, Request/ParamFetcher.php, Response/AllowedMethodsLoader/AllowedMethodsRouterLoader.php, Tests/Functional/Bundle/TestBundle/Controller/SerializerErrorController.php, Tests/Functional/app/config/framework.yml, Tests/Request/AbstractRequestBodyParamConverterTest.php, Tests/Request/ParamFetcherTest.php, Tests/Routing/Loader/RestRouteLoaderTest.php, Tests/View/ViewHandlerTest.php, UPGRADING.md, View/ViewHandler.php, composer.json
fix for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1106
=> enable Symfony 3.0

Resources/doc/5-automatic-route-generation_single-restful-controller.rst
=> fix route pluralization in docs

Decoder/DecoderInterface.php, Decoder/DecoderProviderInterface.php, Decoder/JsonDecoder.php, Decoder/JsonToFormDecoder.php, Decoder/XmlDecoder.php, Inflector/DoctrineInflector.php, Inflector/InflectorInterface.php, Normalizer/ArrayNormalizerInterface.php, Normalizer/CamelKeysNormalizer.php, Normalizer/Exception/NormalizationException.php, Resources/doc/examples/RssHandler.php, Tests/Fixtures/Controller/ParamFetcherController.php, Tests/Functional/SerializerErrorTest.php, Tests/Functional/WebTestCase.php, Tests/Functional/app/AppKernel.php, Tests/Functional/app/JMSSerializer/bundles.php, Tests/Functional/app/RequestBodyParamConverter/bundles.php, Tests/Functional/app/Serializer/bundles.php, Util/StopFormatListenerException.php, Validator/ViolationFormatter.php, Validator/ViolationFormatterInterface.php
This PR fix the bundle headers (thanks to php-cs-fixer).
=> Fix the bundle headers

Negotiation/FormatNegotiator.php, Tests/Negotiation/FormatNegotiatorTest.php
This PR add a test for the ``FormatNegotiator``. Several mistakes are fixed.
=> Test the format negotiator and reorganize it

Negotiation/FormatNegotiator.php, Resources/config/exception_listener.xml, Resources/config/format_listener.xml, Tests/Negotiation/FormatNegotiatorTest.php, UPGRADING.md
supersedes https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1153
fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1151
=> support format priorities

Controller/ExceptionController.php
This PR sync ``ExceptionController::getAndCleanOutputBuffering()`` with the original class:
https://github.com/symfony/symfony/blob/2.4/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php.
The ``Response`` has a new method ``closeOutputBuffers`` since the 2.5.
=> Sync ExceptionController::getAndCleanOutputBuffering() with the original class

.travis.yml, Controller/Annotations/AbstractParam.php, Controller/ExceptionController.php, Decoder/ContainerDecoderProvider.php, Request/ParamFetcher.php, Tests/Controller/Annotations/AbstractParamTest.php, Tests/Request/ParamFetcherTest.php, View/ViewHandler.php
fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1106
=> fix Symfony 3.0

Resources/doc/request_body_converter_listener.rst
As suggested by @lsmith77 on https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1200#issuecomment-156798753.
=> Add validation groups for body converter on doc

Controller/Annotations/AbstractScalarParam.php, Resources/doc/param_fetcher_listener.rst, Tests/Controller/Annotations/AbstractScalarParamTest.php, Tests/Fixtures/Controller/ParamsAnnotatedController.php, Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/ParamFetcherTest.php, Tests/Functional/app/ParamFetcher/bundles.php, Tests/Functional/app/ParamFetcher/config.yml, Tests/Request/ParamReaderTest.php, UPGRADING.md
Relates to https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1190#issuecomment-154802257
=> Rename AbstractScalarParameter::$array to ::$map

.travis.yml
=> Make tests fail on deprecation notices

Controller/Annotations/AbstractParam.php, Controller/Annotations/AbstractScalarParam.php, Request/ParamFetcher.php, Tests/Controller/Annotations/AbstractParamTest.php, Tests/Controller/Annotations/AbstractScalarParamTest.php, Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/ParamFetcherTest.php, Tests/Functional/app/ParamFetcher/config.yml, Tests/Request/ParamFetcherTest.php, Util/ResolverTrait.php, Validator/Constraints/Regex.php, Validator/Constraints/ResolvableConstraintInterface.php
This is an attempt to solve #1217
=> Resolve the container parameter in the ParamFetcher instead of in the parameters

Inflector/DoctrineInflector.php, Inflector/InflectorInterface.php, Negotiation/FormatNegotiator.php, Resources/config/util.xml, Tests/EventListener/FormatListenerTest.php, Tests/EventListener/MimeTypeListenerTest.php, Tests/Negotiation/FormatNegotiatorTest.php, Tests/Routing/Loader/LoaderTest.php, Tests/Util/LegacyFormatNegotiatorTest.php, Tests/Util/ViolationFormatterTest.php, Util/FormatNegotiator.php, Util/FormatNegotiatorInterface.php, Util/Inflector/DoctrineInflector.php, Util/MediaTypeNegotiatorInterface.php, Util/ViolationFormatter.php, Util/ViolationFormatterInterface.php, Validator/ViolationFormatter.php, Validator/ViolationFormatterInterface.php
This PR adds BC layers for #1107
=> add forward compatibility and deprecation notices

Resources/doc/3-listener-support.rst, Resources/doc/format_listener.rst
=> Improve the FormatListener documentation

Controller/Annotations/Param.php, Controller/ExceptionController.php, Decoder/ContainerDecoderProvider.php, DependencyInjection/Compiler/ConfigurationCheckPass.php, DependencyInjection/Compiler/CsrfExtensionPass.php, DependencyInjection/Compiler/ExceptionWrapperHandlerPass.php, DependencyInjection/Compiler/FormatListenerRulesPass.php, DependencyInjection/Compiler/SerializerConfigurationPass.php, DependencyInjection/Compiler/TwigExceptionPass.php, DependencyInjection/Configuration.php, DependencyInjection/FOSRestExtension.php, EventListener/AccessDeniedListener.php, EventListener/AllowedMethodsListener.php, EventListener/BodyListener.php, EventListener/FormatListener.php, EventListener/MimeTypeListener.php, EventListener/ParamFetcherListener.php, EventListener/VersionListener.php, EventListener/ViewResponseListener.php, Request/ParamFetcher.php, Routing/Loader/RestRouteLoader.php, Routing/Loader/RestXmlCollectionLoader.php
=> [1.8] Mark classes/methods as internal

Request/ParamFetcher.php, Request/ParameterBag.php, Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/ParamFetcherTest.php, Tests/Functional/app/ParamFetcher/bundles.php, Tests/Functional/app/ParamFetcher/config.yml, Tests/Request/ParamFetcherTest.php
=>   Fix a bug in the ParamFetcher

Routing/Loader/RestRouteLoader.php, View/ViewHandler.php
=> Fix deprecations

View/ViewHandler.php
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1286#discussion-diff-48508016
=> Remove some getters in the ViewHandler

Controller/TemplatingExceptionController.php
I had some troubles with my API views and noticed some errors in TemplatingExceptionController. 
It's just some use statements that are missing (unless I'm missing something).
=> Fix TemplatingExceptionController

Resources/doc/format_listener.rst
=> Fixed mime type listener reference

View/ViewHandler.php
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1287#issuecomment-167755837
=> Deprecate ViewHandler getters in favor of constructor injections

Context/Adapter/JMSContextAdapter.php, Context/Context.php, DependencyInjection/Compiler/SerializerConfigurationPass.php, DependencyInjection/FOSRestExtension.php, EventListener/ViewResponseListener.php, Request/AbstractRequestBodyParamConverter.php, Resources/config/serializer.xml, Serializer/JMSSerializerAdapter.php, Serializer/Serializer.php, Serializer/SymfonySerializerAdapter.php, Tests/Context/ContextTest.php, Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php, Tests/EventListener/ViewResponseListenerTest.php, Tests/Request/AbstractRequestBodyParamConverterTest.php, Tests/Request/RequestBodyParamConverter20Test.php, Tests/Request/RequestBodyParamConverterTest.php, Tests/View/JsonpHandlerTest.php, Tests/View/ViewHandlerTest.php, Util/ContextHelper.php, View/View.php, View/ViewHandler.php
=> Create a serializer adapter

Routing/Loader/Reader/RestActionReader.php, Tests/Fixtures/Controller/AnnotatedConditionalUsersController.php, Tests/Fixtures/Controller/AnnotatedPrefixedController.php, Tests/Fixtures/Controller/ArticleController.php, Tests/Fixtures/User.php
=> Fix a typo in the RestActionLoader

Serializer/JMSSerializerAdapter.php, Serializer/SymfonySerializerAdapter.php, Tests/Functional/SerializerErrorTest.php
=> Merge 1.8 into master

DependencyInjection/FOSRestExtension.php
=> fix the service tag names being cleared

Routing/Loader/DirectoryRouteLoader.php, Routing/Loader/RestRouteLoader.php, Tests/Routing/Loader/DirectoryRouteLoaderTest.php, composer.json
Make some tweaks suggested by @Ener-Getick in #1339.
=> some tweaks to the directory route loader

Request/RequestBodyParamConverter.php, Resources/config/request_body_param_converter.xml, Tests/Functional/Bundle/TestBundle/Controller/RequestBodyParamConverterController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/RequestBodyParamConverterTest.php, Tests/Functional/app/RequestBodyParamConverter/bundles.php, Tests/Functional/app/RequestBodyParamConverter/config.yml, Tests/Functional/app/RequestBodyParamConverter/routing.yml, UPGRADING.md
Fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1237
=> Define a priority of -50 on the fos_rest.request_body converter

composer.json
See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1354#issuecomment-187678100
=> Forbid SensioFrameworkExtraBundle >= 3.0.13

Resources/doc/index.rst
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1368
=> Fix a warning in the docs

Resources/config/view.xml, Tests/DependencyInjection/FOSRestExtensionTest.php
=> Fixes 1361 - Define the serializer groups parameter as a collection

Controller/TwigExceptionController.php, Resources/doc/2-the-view-layer.rst, Resources/doc/format_listener.rst
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1358#commitcomment-16526786 and https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1372
=> Fix a warning and typos

Controller/TemplatingExceptionController.php, Controller/TwigExceptionController.php, DependencyInjection/FOSRestExtension.php, Tests/Functional/ErrorWithTemplatingFormatTest.php, Tests/Functional/WebTestCase.php, Tests/Functional/app/Serializer/bundles.php, Tests/Functional/app/Serializer/config.yml
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1375
=> Fix the TwigExceptionController

DependencyInjection/Compiler/TwigExceptionPass.php, Resources/doc/4-exception-controller-support.rst
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1410
cc @xabbuh
=> Update the exception listener doc

.travis.yml, Request/ParamFetcher.php, Response/AllowedMethodsLoader/AllowedMethodsRouterLoader.php, Tests/Functional/AllowedMethodsTest.php, Tests/Functional/Bundle/TestBundle/Controller/AllowedMethodsController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/app/AllowedMethodsListener/bundles.php, Tests/Functional/app/AllowedMethodsListener/config.yml
Fixes #1412 and adds tests for the AllowedMethodsListener.
=> Fix the AllowedMethodsLoader when using sf 3.0

Resources/doc/7-manual-route-definition.rst
Documentation update for Manual routes definition the OPTIONS request type, on version 1.7
=> Annotation for OPTIONS route definition added for version 1.7

DependencyInjection/Configuration.php, DependencyInjection/FOSRestExtension.php, Resources/config/exception_listener.xml, Tests/DependencyInjection/FOSRestExtensionTest.php, Tests/Functional/Bundle/TestBundle/Controller/SerializerErrorController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/SerializerErrorTest.php, Tests/Functional/app/Debug/bundles.php, Tests/Functional/app/Debug/config.yml
Backport #1370 to 2.0 (needed to fix the tests)
=> Backport #1370

Context/Context.php, Tests/Context/ContextTest.php
See #1426. I feel that this method is missing.
=> Add setGroups()

Routing/Loader/Reader/RestActionReader.php, Tests/Fixtures/Controller/AnnotatedVersionUserController.php, Tests/Fixtures/Etalon/annotated_version_controller.yml, Tests/Routing/Loader/RestRouteLoaderTest.php
Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1386 and https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1436
=> add version condition to route even without any routing annotations

Resources/config/versioning.xml
See https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1443
=> Fix a service name

Resources/doc/configuration-reference.rst
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1434
=> Fix the docs

CHANGELOG.md
I forgot to mark #1449 as "WIP". So this PR adds the missing pieces.
=> complete the changelog file for 1.7

Controller/ExceptionController.php, DependencyInjection/Configuration.php, DependencyInjection/FOSRestExtension.php, Tests/DependencyInjection/FOSRestExtensionTest.php, Tests/Functional/Bundle/TestBundle/Controller/SerializerErrorController.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/SerializerErrorTest.php, Tests/Functional/app/Debug/bundles.php, Tests/Functional/app/Debug/config.yml
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1441#issuecomment-216763140
=> [1.8] Backport #1370

Resources/doc/body_listener.rst
Or, more presicely, with the login form.
=> Document usage with FOS UserBundle

UPGRADING-2.0.md
This PR adds examples to our UPGRADING file to simplify the migration to 2.0.
=> Add examples to UPGRADE-2.0.md

Routing/Loader/Reader/RestActionReader.php, Tests/Fixtures/Controller/AnnotatedVersionUserController.php, Tests/Fixtures/Etalon/annotated_version_controller.yml, Tests/Functional/Bundle/TestBundle/Controller/Version2Controller.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/VersionTest.php, Tests/Routing/Loader/RestRouteLoaderTest.php
Backport https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1438
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1491
=> Backport #1438

Resources/config/serializer.xml
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1489#issuecomment-219788300
=> Decrease FormErrorNormalizer priority

Resources/doc/versioning.rst
Let's remove this part from 1.8 doc
=> Version annotation exists only in branch 2.0

Routing/Loader/RestRouteLoader.php, Tests/DependencyInjection/Compiler/FormatListenerRulesPassTest.php, Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php, Tests/EventListener/BodyListenerTest.php, Tests/EventListener/FormatListenerTest.php, Tests/EventListener/VersionListenerTest.php, Tests/EventListener/ViewResponseListenerTest.php, Tests/EventListener/ZoneMatcherListenerTest.php, Tests/Request/ParamFetcherTest.php, Tests/Request/ParamReaderTest.php, Tests/Request/RequestBodyParamConverter20Test.php, Tests/Request/RequestBodyParamConverterTest.php, Tests/Routing/Loader/DirectoryRouteLoaderTest.php, Tests/Routing/Loader/LoaderTest.php, Tests/Routing/Loader/RestYamlCollectionLoaderTest.php, Tests/View/JsonpHandlerTest.php, Tests/View/ViewHandlerTest.php
see https://github.com/symfony/symfony/issues/19125
=> Fix phpunit deprecations

Resources/doc/body_listener.rst
This fixes the errors reported by http://symfony.com/doc/build_errors
=> Fixed the syntax of a code example

Resources/doc/view_response_listener.rst
fix this error.
-----
The class "FOS\RestBundle\View\View" is not annotated with @Annotation. Are you sure this class can be used as annotation? If so, then you need to add @Annotation to the _class_ doc comment of "FOS\RestBundle\View\View".
=> same class name

Request/ParamFetcher.php, Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/app/ParamFetcher/config.yml, Tests/Request/ParamFetcherTest.php
Fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1528
=> [ParamFetcher] Fix default resolving

Context/Context.php, Serializer/JMSSerializerAdapter.php, Tests/Context/ContextTest.php
Fix for issue #1536. I don't think it needs more magic than this.
=> #1536 Added support for JMS exclusion strategies

README.md
=> Upgrade warning

Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/ParamFetcherTest.php, Validator/Constraints/Regex.php
=> the Regex constraint is resolvable

EventListener/VersionListener.php, Tests/EventListener/VersionListenerTest.php, Tests/Functional/Bundle/TestBundle/Resources/config/routing.yml, Tests/Functional/VersionTest.php
see https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1604
=> Support path versioning for rendering responses

Request/ParamFetcher.php, Tests/Functional/Bundle/TestBundle/Controller/ParamFetcherController.php, Tests/Functional/ParamFetcherTest.php, Tests/Request/ParamFetcherTest.php
=> fix parameter incompatibles attribute

composer.json
remove the extra spaces between colon and quote and remove Tests namespace from autoload classmap
=> remove extra spaces, remove tests from autoload classmap

DependencyInjection/Compiler/SerializerConfigurationPass.php, DependencyInjection/Configuration.php, Routing/Loader/DirectoryRouteLoader.php, Tests/DependencyInjection/Compiler/ConfigurationCheckPassTest.php, Tests/DependencyInjection/Compiler/SerializerConfigurationPassTest.php, Tests/DependencyInjection/FOSRestExtensionTest.php, Tests/Fixtures/Controller/Directory/NoClass.php, Tests/Functional/ParamFetcherTest.php, Tests/Negotiation/FormatNegotiatorTest.php, Tests/Request/ParamFetcherTest.php, Tests/Request/ParamReaderTest.php, Tests/Request/RequestBodyParamConverterTest.php, Tests/Routing/Loader/RestYamlCollectionLoaderTest.php, Tests/View/ViewHandlerTest.php, Tests/View/ViewTest.php
See https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1611
=> Fix serializers configuration priority

Tests/Functional/VersionTest.php, View/ViewHandler.php
Fix https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1649, https://github.com/symfony/symfony/issues/21974
=> Use the detected mime type as Content-Type

UPGRADING-2.0.md
There is no `RouteRedirect` class, `RouteRedirectView` is correct class name.
=> Actualize RouteRedirectView class name.

Resources/doc/1-setting_up_the_bundle.rst
=> Document correct order with JMSSerializerBundle

DependencyInjection/Configuration.php, DependencyInjection/FOSRestExtension.php, Resources/config/routing.xml, Resources/doc/7-manual-route-definition.rst, Resources/doc/configuration-reference.rst, Routing/Loader/Reader/RestActionReader.php, Tests/Fixtures/Controller/AnnotatedUsersController.php, Tests/Routing/Loader/LoaderTest.php, Tests/Routing/Loader/RestRouteLoaderTest.php
Add support for https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1507
=> Disable 'method_prefix' globally

EventListener/ViewResponseListener.php, View/ViewHandler.php
=> Support custom keys for groups

Resources/config/view.xml
=> add ViewHandlerInterface service alias

DependencyInjection/Compiler/ConfigurationCheckPass.php, composer.json
fixes https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1768
=> Sensio framework extra4.x

EventListener/FormatListener.php, EventListener/ParamFetcherListener.php, Negotiation/FormatNegotiator.php, Request/ParamFetcher.php, Request/RequestBodyParamConverter.php, Routing/Loader/Reader/RestActionReader.php, Routing/Loader/RestXmlCollectionLoader.php, Routing/Loader/RestYamlCollectionLoader.php, Serializer/JMSSerializerAdapter.php, Tests/Functional/app/AppKernel.php, Tests/Request/ParamFetcherTest.php, Tests/Request/RequestBodyParamConverterTest.php, Tests/Routing/Loader/LoaderTest.php, Version/ChainVersionResolver.php, View/ViewHandler.php
=> code style fixes

Resources/config/request.xml
=> add ParamFetcherInterface service alias

Decoder/ContainerDecoderProvider.php, DependencyInjection/FOSRestExtension.php
=> use a lazy loading service locator for decoders

Tests/Functional/app/config/default.yml
ping @lsmith77 @GuilhemN What do you think?
=> suppress unneeded noise in tests

.travis.yml, composer.json
* drop the `minimum-stability` setting in `composer.json`
* set `minimum-stability` only when needed instead
* use `symfony/lts` instead of `symfony/symfony`
=> improve the Travis CI config

Routing/Loader/RestRouteLoader.php
I saw https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1810 and I thought it would solve https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1804 but it didn't. I saw there is one more place where we need to add `.yaml` and this fixed my issue.
closes #1804
=> Add support for yaml routes

Resources/config/serializer.xml, Serializer/Normalizer/FormErrorNormalizer.php
Follow up of PR #1884 in order to fix #1883.
=> Remove translator dependency

DependencyInjection/Compiler/JMSFormErrorHandlerPass.php, Serializer/Normalizer/FormErrorHandler.php, Tests/Functional/DependencyInjectionTest.php
Fixes #1806 and replaces #1876 and #1877.
ping @GuilhemN @tarjei @GijsL
=> prefer decoration over parameter replacements

Routing/Loader/RestRouteLoader.php, Tests/Routing/Loader/RestYamlCollectionLoaderTest.php
Fixes https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1904#discussion_r199572760
=> Simplify version check

DependencyInjection/FOSRestExtension.php, EventListener/VersionExclusionListener.php, EventListener/VersionListener.php, Resources/config/versioning.xml, Routing/Loader/Reader/RestActionReader.php, Tests/EventListener/VersionExclusionListenerTest.php, Tests/EventListener/VersionListenerTest.php, Tests/Fixtures/Controller/AnnotatedVersionUserController.php, Tests/Fixtures/Etalon/annotated_version_controller.yml, Tests/Functional/Bundle/TestBundle/Controller/Version2Controller.php, Tests/Functional/Bundle/TestBundle/Controller/VersionController.php, Tests/Functional/Bundle/TestBundle/Resources/views/Version/version.html.twig, Tests/Functional/VersionTest.php, Tests/Routing/Loader/RestRouteLoaderTest.php
This PR is based on #1639. Author of the original PR hasn't been responding since 2016.
I rebased commits from the original PR and implemented some changes requested by @GuilhemN.
- Issues with URI versioning (#1529, #1691)
- Version annotation not adding condition for API versioning (#1491)
=> Fix issues with URI versioning and version annotation condition

Resources/doc/1-setting_up_the_bundle.rst
In Symfony 4.0 there are a new bundle registration procedure
=> [docs] Symfony 4.0 bundle registration

DependencyInjection/Configuration.php
=> don't use the deprecated interface with Symfony 4.2

Controller/Annotations/AbstractScalarParam.php, Resources/doc/param_fetcher_listener.rst, Tests/Controller/Annotations/AbstractScalarParamTest.php, Tests/Functional/ParamFetcherTest.php
This implements arrays of constraints as explained in issue #1748
=> Allow arrays of constraints on parameters

Serializer/SymfonySerializerAdapter.php
Resolves issue https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1996
=> fix: symfony serializer skip_null_values configuration

Resources/doc/versioning.rst
Hardcode the list instead of auto-enumeration
=> Fix enumerated list

.travis.yml, Controller/TemplatingExceptionController.php, Negotiation/FormatNegotiator.php, Request/ParameterBag.php, Resources/doc/2-the-view-layer.rst, Resources/doc/3-listener-support.rst, Resources/doc/4-exception-controller-support.rst, Resources/doc/5-automatic-route-generation_single-restful-controller.rst, Resources/doc/6-automatic-route-generation_multiple-restful-controllers.rst, Resources/doc/body_listener.rst, Resources/doc/format_listener.rst, Resources/doc/index.rst, Resources/doc/param_fetcher_listener.rst, Resources/doc/request_body_converter_listener.rst, Resources/doc/versioning.rst, Resources/doc/view_response_listener.rst
=> Remove outdated doc

Controller/ExceptionController.php
See https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/ErrorRenderer/Exception/FlattenException.php
=> Fix compatibility to new Symfony FlattenException

EventListener/ExceptionListener.php, Resources/config/exception_listener.xml
Replaces https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2018
=> Remove deprecation warning about final ExceptionListener

Resources/doc/5-automatic-route-generation_single-restful-controller.rst
=> fix method name

DependencyInjection/Configuration.php, DependencyInjection/FOSRestExtension.php, Resources/config/routing.xml, Routing/Loader/RestRouteLoader.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/FOSRestExtensionTest.php, Tests/Functional/DependencyInjectionTest.php, Tests/Functional/app/AllowedMethodsListener/config.yml, Tests/Functional/app/Configuration/config.yml, Tests/Functional/app/Debug/config.yml, Tests/Functional/app/JMSSerializer/config.yml, Tests/Functional/app/ParamFetcher/config.yml, Tests/Functional/app/RequestBodyParamConverter/config.yml, Tests/Functional/app/RequestBodyParamConverterFrameworkBundle/config.yml, Tests/Functional/app/Routing/config.yml, Tests/Functional/app/Serializer/config.yml, Tests/Functional/app/Version/config.yml, Tests/Functional/app/ViewResponseListener/config.yml, Tests/Routing/Loader/LoaderTest.php, UPGRADING-2.8.md, UPGRADING-3.0.md, phpunit.xml.dist
=> deprecate using the ControllerNameParser

EventListener/ViewResponseListener.php
fixes sensiolabs/SensioFrameworkExtraBundle#649
=> fix SensioFrameworkExtraBundle compatibility

composer.json
=> don't try to autoload resource files

Resources/config/serializer.xml
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2106#issuecomment-595304595
=> do not flag the serializer adapter services as lazy

Controller/Annotations/RouteResource.php, Controller/Annotations/Version.php, Resources/doc/index.rst, Resources/doc/versioning.rst, Routing/ClassResourceInterface.php, Routing/Loader/ClassUtils.php, Routing/RestRouteCollection.php, Tests/Functional/Bundle/TestBundle/Controller/ArticleController.php, UPGRADING-2.8.md
Add some missing deprecations from #2152 for #1954
=> add missing deprecations for automatic route generation

Controller/Annotations/NamePrefix.php, Controller/Annotations/NoRoute.php, Controller/Annotations/Prefix.php, Tests/Request/ParamReaderTest.php, UPGRADING-2.8.md
Add some leftover deprecations from #2152 for #1954
=> more leftover routing deprecations

Resources/doc/annotations-reference.rst, Resources/doc/request_body_converter_listener.rst
=> remove more deprecated documentation

Serializer/Normalizer/FlattenExceptionHandler.php, Serializer/Normalizer/FlattenExceptionNormalizer.php, Tests/Functional/SerializerErrorTest.php
=> send RFC 7807 compatible content type header

DependencyInjection/FOSRestExtension.php, Tests/DependencyInjection/FOSRestExtensionTest.php
=> fix setting view handler serializer options

README.md
Fixed the invalid link in Readme.md.
=> Fixed the invalid link in Readme.md.

README.md
I suggest to remove stuff that tends to outdate too often and no longer promote deprecated features.
=> clean up the readme file

CHANGELOG.md, UPGRADING-3.0.md
=> improve route loader upgrade instructions

CHANGELOG.md, Serializer/Normalizer/FlattenExceptionNormalizer.php
=> do not implement (possibly) not available interface
